# Generated by Django 3.1.4 on 2021-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreg',
            name='businessname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
