# Generated by Django 3.1.4 on 2021-04-09 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20210409_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantitems',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cc.businessreg'),
        ),
    ]
