# Generated by Django 3.1.4 on 2021-06-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_businessreg_businessverification_comment_communityposts_communityrequests_confirmedorders_givebackre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='pincode',
        ),
    ]
