# Generated by Django 3.1.4 on 2021-04-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_businessreg_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cooking_instruction',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
