# Generated by Django 3.1.4 on 2021-04-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_orderitem_cooking_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedorders',
            name='Order_Delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
