# Generated by Django 3.1.4 on 2021-04-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0009_auto_20210411_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='Area_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cc.area'),
        ),
    ]
