# Generated by Django 3.1.4 on 2021-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0010_auto_20210411_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined_in_community',
            field=models.BooleanField(default=False),
        ),
    ]
