# Generated by Django 3.1.4 on 2021-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0011_userprofile_joined_in_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreg',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_reg_pics'),
        ),
    ]
