# Generated by Django 3.1.4 on 2021-04-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0013_restaurantitems_available_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantitems',
            name='available_today',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
